spring:
  application:
    name: http-server-feign
  cloud:
    openfeign:
      client:
        config:
          feignServer:
            url: http://127.0.0.1:8080/
            loggerLevel: FULL


